config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'

  post    '/attend',        to: 'attendances#create'
  get     '/attend',        to: 'attendances#create'
  delete  '/unattend',      to: 'attendances#destroy'


  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  
  resources :sessions, only: [:create, :new, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past_events, -> {where("date < ?", DateTime.current)}
  scope :upcoming_events, -> {where("date > ?", DateTime.current)}

  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user

  validates :title, presence: true, length: { minimum: 6, maximum: 140 }
  validates :description, presence: true, length: { minimum: 15, maximum: 1500 }
  validates :date, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events,  class_name: 'Event', foreign_key: 'creator_id'

  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 140 }

  def previous_events
    attended_events.where("date < ?", Time.current)
  end

  def upcoming_events
    attended_events.where("date > ?", Time.current)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  include EventsHelper
  
  private 
  def logged_in_user
    unless logged_in? store_location
      flash[:danger] = "Please log in."
      redirect_to login_url 
    end 
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :create
  before_action :correct_user_or_event_creator, only: :destroy

  def create
    @event = Event.find(params[:event_id])
    @event.attendees << current_user
    redirect_to @event
  end

  def destroy
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    @event.attendees.delete(@user)
    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in?, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @event = Event.all
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Your event has been created."
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Your event has been updated."
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Event has been cancelled."
    redirect_to root_path
  end


  private

  def signed_in?
    unless current_user
      flash[:info] = "You are not signed in."
      redirect_to login_path
    end
  end


  def event_params
    params.require(:event).permit(:description, :date, :title, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_to user_path(user.id)
      flash.now[:success] = 'You are signed in!'
    else
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "Logged out."
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    #@created_events = current_user.created_events
    #@attended_events = current_user.attended_events
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.previous_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'User has been created'
      redirect_to @user

    else
      render 'new'
      flash.now[:danger] = 'User could not be created'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "This user has been deleted."
    redirect_to root_path
  end

  private

  def signed_in?
    unless current_user
      redirect_to new_session_path, success: 'you are not signed in!'
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def correct_user_or_event_creator
    unless correct_user || event_creator
      flash[:warning] = "You are not authorized for this action."
      redirect_to root_path
    end
  end

  def event_creator
    creator = Event.find(params[:event_id]).creator
    current_user == creator
  end

  def correct_user
    user = User.find(params[:user_id])
    current_user == user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user 
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !session[:user_id].nil?
  end

  def log_out
    session.delete(:user_id)
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_errors.html.erb
<div class="alert-warning">
	<% if @event.errors.any? %>
		<ul>
			<h5>This form contains <%= pluralize(@event.errors.count, "error") %>:</h5>
			<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/events/_event.html.erb
<li class="list-group-item">
	<%= link_to event.description, event %>
	<br>

</li>

app/views/events/_form.html.erb
<div class="pb-5">
  <% render 'errors'%>
  <%= bootstrap_form_for(@event) do |f| %>
    <div class="pt-2 shadow pb-5 mt-5 container col-lg-4 col-md-5 mb-5">
      <%= f.text_field :title, class: "text-black bg-light" %>
      <%= f.text_field :location, class: "text-black bg-light" %>
      <%= f.text_area :description, class: "text-black bg-light" %>
      <%= f.datetime_select :date, class: "text-black bg-light"%>
      <div class="d-flex justify-content-between">
        <%= link_to "Cancel", root_path, class: "btn-primary btn-lg" %>
        <%= f.submit "Submit", class: "btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<% provide(:title, "Events") %>

<h1>Events</h1>

<hr>

<h2>Upcoming</h2>

<ul class="list-group">
	<%= render @upcoming_events %>
</ul>

<hr>

<h2>Past</h2>

<ul class="list-group">
	<%= render @past_events %>
</ul>

app/views/events/new.html.erb
 
<h1>Create a new event!</h1>
<h1>New Event</h1>

<hr>

<%= render 'form' %>

app/views/events/show.html.erb
<div>
<h1><%= @event.title %></h1>

<p>Created by <%= @event.creator.email%></p>

<%= @event.creator.name%>

<hr>

<p>Location: <%= @event.location %></p>

<p>Time: <%= @event.date.strftime("%I:%M %p, %D")%></p>

<hr>

<p> <%= @event.description%> </p>

<hr>

<h2>Attending</h2>

	
</div>

app/views/layouts/_footer.html.erb
 <footer class="navbar fixed-bottom navbar-dark">
	<ul class="nav">
		<li class="nav-item">
			<%= link_to "Home", root_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "About", about_path, class: "nav-link" %>
		</li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-light">
	<%= link_to "Private-Events", root_path, class: "navbar-brand" %>
	<ul class="nav">
		<li class="nav-item">
			<%= link_to "New Event", new_event_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "Events", events_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "Users", users_path, class: "nav-link" %>
		</li>
		<% if !logged_in? %>
			<li class="nav-item">
				<%= link_to "Sign Up", signup_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Log In", login_path, class: "nav-link" %>
			</li>
		<% else %>
			<li class="nav-item">
				<%= link_to "Account", current_user, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %>
			</li>
		<% end %>
	</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

  	<div class="center">
    	<%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/_guest_home.html.erb
<p> Welcome </p>
<%= link_to "Sign Up", signup_path, class: "btn-primary btn-lg" %>

app/views/static_pages/_user_home.html.erb
<p>You are logged in as <%# current_user.username %>!</p>

<%= link_to "Create Event", new_event_path, class: "btn-primary btn-lg" %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Private-Events</h1>

<hr>

<% if logged_in? %>
	<%= render 'user_home' %>
<% else %>
	<%= render 'guest_home' %>
<% end %>

app/views/users/_errors.html.erb
<div class="alert-warning">
	<% if @user.errors.any? %>
		<ul>
			<h5>This form contains <%= pluralize(@user.errors.count, "error") %>:</h5>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= render 'errors' %>
  <div class="form-group">
		<h4><%= f.label :email %></h4>
		<%= f.text_field :email, class: "form-control-lg" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :password %></h4>
		<%= f.password_field :password, class: "form-control-lg" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :password_confirmation %></h4>
		<%= f.password_field :password_confirmation, class: "form-control-lg" %>
	</div>
	<%= f.submit "Submit", class: "btn-primary btn-lg" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<hr>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="col-12">
<h1>Events</h1>
<hr>

<h2>Created Events</h2>

<%= render @user.created_events %>

<hr>

<h2>Upcomming Events</h2>

<%= render @user.attended_events.upcoming_events %>

<hr>

<h2>Attended Events</h2>

<%= render @user.attended_events.past_events %>